-- Generates keymaps.md from TWO live sources, merged:
--   1) lazy.nvim plugin `keys` specs (catches lazy-loaded plugin keymaps without
--      pressing them — they never materialize as real maps until first use)
--   2) vim.api.nvim_get_keymap after firing VeryLazy (catches keymaps.lua and
--      eagerly-set plugin maps)
-- Never hand-edit keymaps.md.
-- Run:  nvim --headless "+luafile scripts/dump-keymaps.lua" +qa
-- (Must be +luafile, NOT -l: `nvim -l` runs a bare nvim and never sources your
--  init.lua, so no plugins/keymaps would be loaded.)

-- fire VeryLazy so LazyVim loads its config/keymaps.lua
pcall(vim.api.nvim_exec_autocmds, "User", { pattern = "VeryLazy", modeline = false })
vim.wait(300)

local modes = { n = "Normal", i = "Insert", v = "Visual/Select", x = "Visual Block", t = "Terminal", c = "Command" }
local order = { "n", "i", "v", "x", "t", "c" }

-- collected[mode][lhs] = desc
local collected = {}
for _, m in ipairs(order) do
  collected[m] = {}
end

local function add(mode, lhs, desc)
  if not lhs or lhs == "" or not desc or desc == "" then
    return
  end
  if desc:match("^:") or desc:match("%-default$") then
    return -- nvim/LazyVim builtins like ":help X-default"
  end
  if collected[mode] and not collected[mode][lhs] then
    collected[mode][lhs] = desc
  end
end

-- source 1: lazy plugin keys specs
local ok, lazy = pcall(require, "lazy")
if ok then
  for _, p in ipairs(lazy.plugins()) do
    local keys = type(p.keys) == "table" and p.keys or {}
    for _, k in ipairs(keys) do
      if type(k) == "table" then
        local lhs = k[1]
        local kmodes = k.mode or "n"
        if type(kmodes) == "string" then
          kmodes = { kmodes }
        end
        for _, mode in ipairs(kmodes) do
          add(mode, lhs, k.desc or ("[" .. p.name .. "]"))
        end
      end
    end
  end
end

-- source 2: live keymap table
for _, mode in ipairs(order) do
  for _, m in ipairs(vim.api.nvim_get_keymap(mode)) do
    add(mode, m.lhs, m.desc)
  end
end

local out = {
  "# Keymaps (auto-generated)",
  "",
  "> Generated by `scripts/dump-keymaps.lua` from lazy plugin specs + the live keymap table.",
  "> **Do not hand-edit.** Regenerate: `nvim --headless -l scripts/dump-keymaps.lua`.",
  "> Only keymaps that carry a `desc` are listed. Live source of truth is which-key (`<leader>`).",
  "",
}

for _, mode in ipairs(order) do
  local lhss = {}
  for lhs in pairs(collected[mode]) do
    lhss[#lhss + 1] = lhs
  end
  if #lhss > 0 then
    table.sort(lhss)
    out[#out + 1] = ("## %s mode"):format(modes[mode])
    out[#out + 1] = ""
    out[#out + 1] = "| Key | Description |"
    out[#out + 1] = "|---|---|"
    for _, lhs in ipairs(lhss) do
      local k = lhs:gsub("^ ", "<leader>"):gsub("^<Space>", "<leader>"):gsub("|", "\\|")
      local d = collected[mode][lhs]:gsub("|", "\\|")
      out[#out + 1] = ("| `%s` | %s |"):format(k, d)
    end
    out[#out + 1] = ""
  end
end

local path = vim.fn.stdpath("config") .. "/keymaps.md"
vim.fn.writefile(out, path)
print("wrote " .. path .. " (" .. #out .. " lines)")
