return {}
-- return {
--   "yetone/avante.nvim",
--   event = "VeryLazy",
--   lazy = false,
--   version = false,
--
--   init = function()
--     vim.env.OPENAI_API_KEY = "ollama"
--   end,
--
--   opts = {
--     provider = "openai",
--
--     providers = {
--       openai = {
--         endpoint = "http://localhost:11434/v1",
--         model = "llama3.1",
--         -- CRITICAL: Disable tools support for Ollama
--         use_xml_format = false,
--         supports_tools = false,
--         extra_request_body = {
--           temperature = 0.7,
--           max_tokens = 1024,
--           stream = false,
--         },
--       },
--     },
--
--     -- IMPORTANT: Disable system prompt features that need tools
--     system_prompt = "",
--
--     behaviour = {
--       auto_suggestions = false,
--       auto_set_highlight_group = true,
--       auto_set_keymaps = true,
--       auto_apply_diff_after_generation = false,
--       support_paste_from_clipboard = true,
--     },
--
--     mappings = {
--       diff = {
--         ours = "co",
--         theirs = "ct",
--         all_theirs = "ca",
--         both = "cb",
--         cursor = "cc",
--         next = "]x",
--         prev = "[x",
--       },
--       suggestion = {
--         accept = "<M-l>",
--         next = "<M-]>",
--         prev = "<M-[>",
--         dismiss = "<C-]>",
--       },
--       jump = {
--         next = "]]",
--         prev = "[[",
--       },
--       submit = {
--         normal = "<CR>",
--         insert = "<C-s>",
--       },
--     },
--
--     hints = { enabled = true },
--
--     windows = {
--       position = "right",
--       wrap = true,
--       width = 30,
--       sidebar_header = {
--         align = "center",
--         rounded = true,
--       },
--     },
--
--     highlights = {
--       diff = {
--         current = "DiffText",
--         incoming = "DiffAdd",
--       },
--     },
--
--     diff = {
--       autojump = true,
--       list_opener = "copen",
--     },
--   },
--
--   build = "make",
--
--   dependencies = {
--     "nvim-treesitter/nvim-treesitter",
--     "stevearc/dressing.nvim",
--     "nvim-lua/plenary.nvim",
--     "MunifTanjim/nui.nvim",
--     "nvim-tree/nvim-web-devicons",
--     {
--       "HakonHarnes/img-clip.nvim",
--       event = "VeryLazy",
--       opts = {
--         default = {
--           embed_image_as_base64 = false,
--           prompt_for_file_name = false,
--           drag_and_drop = {
--             insert_mode = true,
--           },
--           use_absolute_path = true,
--         },
--       },
--     },
--     {
--       "MeanderingProgrammer/render-markdown.nvim",
--       opts = {
--         file_types = { "markdown", "Avante" },
--       },
--       ft = { "markdown", "Avante" },
--     },
--   },
--
--   keys = {
--     {
--       "<leader>aa",
--       function()
--         require("avante.api").ask()
--       end,
--       desc = "Avante: Ask AI",
--       mode = { "n", "v" },
--     },
--     {
--       "<leader>ar",
--       function()
--         require("avante.api").refresh()
--       end,
--       desc = "Avante: Refresh",
--       mode = "n",
--     },
--     {
--       "<leader>ae",
--       function()
--         require("avante.api").edit()
--       end,
--       desc = "Avante: Edit",
--       mode = "v",
--     },
--     {
--       "<leader>at",
--       function()
--         require("avante").toggle()
--       end,
--       desc = "Avante: Toggle",
--       mode = "n",
--     },
--     {
--       "<leader>af",
--       function()
--         require("avante.api").focus()
--       end,
--       desc = "Avante: Focus",
--       mode = "n",
--     },
--     {
--       "<leader>as",
--       function()
--         require("avante.api").suggest()
--       end,
--       desc = "Avante: Suggest",
--       mode = { "n", "v" },
--     },
--   },
-- }
