return {}
-- return {
--   "nvimtools/none-ls.nvim",
--   optional = true,
--   opts = function(_, opts)
--     local nls = require("null-ls")
--     opts.sources = opts.sources or {}
--
--     -- Ensure eslint_d is available before adding it
--     local has_eslint_d = vim.fn.executable("eslint_d") == 1
--
--     -- Add Biome for formatting
--     table.insert(opts.sources, nls.builtins.formatting.biome)
--
--     -- Add eslint_d only if installed
--     if has_eslint_d then
--       local eslint_config = {
--         nls.builtins.diagnostics.eslint_d.with({
--           condition = function(utils)
--             return utils.root_has_file({ ".eslintrc.js", ".eslintrc.json", ".eslintrc.yml" })
--           end,
--         }),
--         nls.builtins.formatting.eslint_d.with({
--           condition = function(utils)
--             return utils.root_has_file({ ".eslintrc.js", ".eslintrc.json", ".eslintrc.yml" })
--           end,
--         }),
--       }
--       vim.list_extend(opts.sources, eslint_config)
--     else
--       vim.notify("eslint_d is not installed! Skipping eslint_d setup.", vim.log.levels.WARN)
--     end
--
--     -- Ensure formatting runs on save
--     opts.on_attach = function(client, bufnr)
--       if client.supports_method("textDocument/formatting") then
--         vim.api.nvim_create_autocmd("BufWritePre", {
--           buffer = bufnr,
--           callback = function()
--             vim.lsp.buf.format({ bufnr = bufnr })
--           end,
--         })
--       end
--     end
--   end,
-- }
